Repository RedHatInsights/topological_inventory-api, pull requests merged in 2018-12, with the labels that each got.

#71 Remove the DATABASE_URL from the entrypoint script
  docker-assets/entrypoint
Labels: bug

#80 Filter out encrypted values on serialization
  config/initializers/application_record_serializing.rb
  lib/open_api/serializer.rb
  spec/lib/open_api/serializing_spec.rb
Labels: enhancement

#82 Add primary collection actions for Authentications
  .travis.yml
  app/controllers/api/v0/authentications_controller.rb
  app/controllers/api/v0x0.rb
  config/routes.rb
  public/doc/swagger-2-v0.0.1.yaml
  spec/controllers/api/v0x0/authentications_controller_spec.rb
  spec/swagger_spec.rb
Labels: enhancement, unmergeable
