Repository RedHatInsights/topological_inventory-api, pull requests merged in 2019-06, with the labels that each got.

#194 Support GraphQL
  app/controllers/api/graphql_controller.rb
  config/routes.rb
  lib/tasks/openapi_generate.rake
  public/doc/openapi-3-v1.0.0.json
  spec/requests/api/graphql_controller_spec.rb
Labels: enhancement

#203 Adjust regex pattern based on manageiq-api-common#79
  lib/tasks/openapi_generate.rake
  public/doc/openapi-3-v0.1.0.json
  public/doc/openapi-3-v1.0.0.json
Labels: bug

#205 Add endpoint for CFME manifest
  app/controllers/api/cfme/manifest_controller.rb
  config/cfme/manifest_5_11.json
  config/routes.rb
  spec/requests/api/cfme/manifest_spec.rb
  spec/swagger_spec.rb
Labels: enhancement

#189 Entitlement enforcement
  app/controllers/application_controller.rb
  spec/controllers/application_controller_spec.rb
  spec/support/tenant_identity.rb
Labels: enhancement

#206 Updated the openapi generator to use the new graphql description
  lib/tasks/openapi_generate.rake
  public/doc/openapi-3-v1.0.0.json
Labels: wip
