Repository RedHatInsights/topological_inventory-api, pull requests merged in 2019-02, with the labels that each got.

#109 Validate create params
  app/controllers/api/v0/authentications_controller.rb
  app/controllers/api/v0/container_groups_controller.rb
  app/controllers/api/v0/container_images_controller.rb
  app/controllers/api/v0/container_nodes_controller.rb
  app/controllers/api/v0/container_projects_controller.rb
  app/controllers/api/v0/container_templates_controller.rb
  app/controllers/api/v0/containers_controller.rb
  app/controllers/api/v0/endpoints_controller.rb
  app/controllers/api/v0/flavors_controller.rb
  app/controllers/api/v0/orchestration_stacks_controller.rb
  app/controllers/api/v0/service_instances_controller.rb
  app/controllers/api/v0/service_offerings_controller.rb
  app/controllers/api/v0/service_plans_controller.rb
  app/controllers/api/v0/source_types_controller.rb
  app/controllers/api/v0/sources_controller.rb
  app/controllers/api/v0/tasks_controller.rb
  app/controllers/api/v0/vms_controller.rb
  app/controllers/api/v0/volume_attachments_controller.rb
  app/controllers/api/v0/volume_types_controller.rb
  app/controllers/api/v0/volumes_controller.rb
  app/controllers/api/v0x1.rb
  app/controllers/api/v0x1/mixins/create_mixin.rb
  app/controllers/api/v0x1/mixins/index_mixin.rb
  app/controllers/application_controller.rb
  lib/open_api/docs/doc_v2.rb
  lib/open_api/docs/object_definition.rb
  public/doc/swagger-2-v0.0.1.yaml
  public/doc/swagger-2-v0.1.0.yaml
  spec/controllers/api/v0x1/authentications_controller_spec.rb
  spec/controllers/api/v0x1/endpoints_controller_spec.rb
  spec/controllers/api/v0x1/mixins/create_mixin_spec.rb
  spec/controllers/api/v0x1/sources_controller_spec.rb
Labels: enhancement

#110 Validate list params
  app/controllers/api/v0/authentications_controller.rb
  app/controllers/api/v0/container_groups_controller.rb
  app/controllers/api/v0/container_images_controller.rb
  app/controllers/api/v0/container_nodes_controller.rb
  app/controllers/api/v0/container_projects_controller.rb
  app/controllers/api/v0/container_templates_controller.rb
  app/controllers/api/v0/containers_controller.rb
  app/controllers/api/v0/endpoints_controller.rb
  app/controllers/api/v0/flavors_controller.rb
  app/controllers/api/v0/mixins/index_mixin.rb
  app/controllers/api/v0/mixins/update_mixin.rb
  app/controllers/api/v0/orchestration_stacks_controller.rb
  app/controllers/api/v0/service_instances_controller.rb
  app/controllers/api/v0/service_offering_icons_controller.rb
  app/controllers/api/v0/service_offerings_controller.rb
  app/controllers/api/v0/service_plans_controller.rb
  app/controllers/api/v0/source_types_controller.rb
  app/controllers/api/v0/sources_controller.rb
  app/controllers/api/v0/tags_controller.rb
  app/controllers/api/v0/tasks_controller.rb
  app/controllers/api/v0/vms_controller.rb
  app/controllers/api/v0/volume_attachments_controller.rb
  app/controllers/api/v0/volume_types_controller.rb
  app/controllers/api/v0/volumes_controller.rb
  app/controllers/api/v0x1.rb
  app/controllers/api/v0x1/mixins/destroy_mixin.rb
  app/controllers/api/v0x1/mixins/index_mixin.rb
  app/controllers/api/v0x1/mixins/update_mixin.rb
  app/controllers/application_controller.rb
  lib/open_api/docs/object_definition.rb
  spec/controllers/api/v0x0/mixins/update_mixin_spec.rb
  spec/controllers/api/v0x1/authentications_controller_spec.rb
  spec/controllers/api/v0x1/endpoints_controller_spec.rb
  spec/controllers/api/v0x1/mixins/destroy_mixin_spec.rb
  spec/controllers/api/v0x1/mixins/update_mixin_spec.rb
  spec/controllers/api/v0x1/sources_controller_spec.rb
Labels: enhancement

#111 Expose archived_at to all relevant collections
  public/doc/swagger-2-v0.0.1.yaml
  public/doc/swagger-2-v0.1.0.yaml
Labels: enhancement

#115 Fix allowed create/update params for endpoints
  app/controllers/api/v0/endpoints_controller.rb
  public/doc/swagger-2-v0.0.1.yaml
  public/doc/swagger-2-v0.1.0.yaml
  spec/controllers/api/v0x0/endpoints_controller_spec.rb
  spec/controllers/api/v0x1/endpoints_controller_spec.rb
Labels: bug

#113 Add /internal/v0.0/authentications/:id api
  Gemfile
  app/controllers/internal/v0/authentications_controller.rb
  app/controllers/internal/v0x0.rb
  config/routes.rb
  lib/open_api/serializer.rb
  spec/controllers/internal/v0x0/authentications_controller_spec.rb
  spec/lib/open_api/serializing_spec.rb
  spec/swagger_spec.rb
Labels: enhancement

#117 Fix swagger
  lib/open_api/docs/component_collection.rb
  lib/open_api/docs/doc_v2.rb
  public/doc/swagger-2-v0.1.0.yaml
  spec/support/json_schema_matcher.rb
Labels: bug

#119 Update ID references in v0.0 swagger after PR#117
  public/doc/swagger-2-v0.0.1.yaml
Labels: bug

#120 Fix generator to produce valid swagger yaml
  lib/tasks/swagger_generate.rake
  public/doc/swagger-2-v0.1.0.yaml
Labels: enhancement

#121 Return a helpful error document when parsing the request body
  app/controllers/application_controller.rb
  lib/topological_inventory/api/body_parse_error.rb
  lib/topological_inventory/api/error_document.rb
  lib/topological_inventory/api/exception.rb
Labels: enhancement

#126 Allow for subcollection requests on a polymorphic relation
  app/controllers/application_controller.rb
  config/routes.rb
  public/doc/swagger-2-v0.1.0.yaml
Labels: bug, enhancement

#114 Add /v*/openapi.json to fetch the swagger yaml
  app/controllers/api/v0x1.rb
  config/routes.rb
  public/doc/swagger-2-v0.1.0.yaml
Labels: enhancement

#129 Generate definitions based on models
  lib/tasks/swagger_generate.rake
  public/doc/swagger-2-v0.1.0.yaml
  spec/requests/api/v0.1/source_types_spec.rb
Labels: enhancement

#127 Add Availabilities
  app/controllers/api/v0/availabilities_controller.rb
  app/controllers/api/v0x1.rb
  config/routes.rb
  public/doc/swagger-2-v0.1.0.yaml
Labels: enhancement

#138 Fix undefined raise_unless_primary_instance_exists
  app/controllers/api/v0/availabilities_controller.rb
  app/controllers/api/v0x1.rb
Labels: bug

#103 Async service ordering
  Gemfile
  app/controllers/api/v0/service_plans_controller.rb
  spec/controllers/api/v0x0/service_plans_controller_spec.rb
  spec/controllers/api/v0x1/service_plans_controller_spec.rb
Labels: enhancement

#140 IDReadOnly was removed in PR #131
  lib/tasks/swagger_generate.rake
  public/doc/swagger-2-v0.1.0.yaml
Labels: bug

#141 Add columns needed for host inventory sync
  lib/tasks/swagger_generate.rake
  public/doc/swagger-2-v0.1.0.yaml
Labels: enhancement
