Repository RedHatInsights/topological_inventory-api, pull requests merged in 2020-04, with the labels that each got.

#298 Pin insights-api-common to 3.8 to fix travis failure
  Gemfile
Labels: bug

#300 Update run_rails_server to fail to start container if migrations fail
  Gemfile
  docker-assets/run_rails_server
Labels: WAIT-TO-MERGE

#301 Rename task_id key to id
  app/controllers/api/v1/tasks_controller.rb
  spec/controllers/api/v1x0/tasks_controller_spec.rb
Labels: enhancement
